// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Sprint02.Data;

#nullable disable

namespace Sprint02.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251108042116_AddUniqueStatusConstraint")]
    partial class AddUniqueStatusConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Sprint02.Models.Aluguel", b =>
                {
                    b.Property<int>("IdAluguel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("id_aluguel");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAluguel"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dataFim");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("dataInicio");

                    b.Property<int>("MotoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("fk_moto_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("status");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("fk_usuario_id");

                    b.Property<double>("ValorTotal")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("valorTotal");

                    b.HasKey("IdAluguel");

                    b.HasIndex("MotoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Alugueis");
                });

            modelBuilder.Entity("Sprint02.Models.Moto", b =>
                {
                    b.Property<int>("IdMoto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMoto"));

                    b.Property<int>("IdStatus")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("IdTipo")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("NmChassi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("nm_chassi");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("placa");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("unidade");

                    b.HasKey("IdMoto");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdTipo");

                    b.HasIndex("NmChassi")
                        .IsUnique();

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("T_MOTO");
                });

            modelBuilder.Entity("Sprint02.Models.StatusMoto", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("status");

                    b.HasKey("IdStatus");

                    b.ToTable("T_STATUS_MOTO");
                });

            modelBuilder.Entity("Sprint02.Models.TipoMoto", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("NomeTipo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome_tipo");

                    b.HasKey("IdTipo");

                    b.ToTable("T_TIPO_MOTO");
                });

            modelBuilder.Entity("Sprint02.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)")
                        .HasColumnName("senha");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("T_USUARIO");
                });

            modelBuilder.Entity("Sprint02.Models.Aluguel", b =>
                {
                    b.HasOne("Sprint02.Models.Moto", "Moto")
                        .WithMany()
                        .HasForeignKey("MotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Aluguel_Moto");

                    b.HasOne("Sprint02.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Aluguel_Usuario");

                    b.Navigation("Moto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Sprint02.Models.Moto", b =>
                {
                    b.HasOne("Sprint02.Models.StatusMoto", "status")
                        .WithMany("Motos")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Moto_StatusMoto");

                    b.HasOne("Sprint02.Models.TipoMoto", "modelo")
                        .WithMany("Motos")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Moto_TipoMoto");

                    b.Navigation("modelo");

                    b.Navigation("status");
                });

            modelBuilder.Entity("Sprint02.Models.StatusMoto", b =>
                {
                    b.Navigation("Motos");
                });

            modelBuilder.Entity("Sprint02.Models.TipoMoto", b =>
                {
                    b.Navigation("Motos");
                });
#pragma warning restore 612, 618
        }
    }
}
